import { Configuration, OpenAIApi } from "openai";

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);

export default async function (req, res) {
  const completion = await openai.createCompletion("text-davinci-002", {
    prompt: generatePrompt(req.body.blogTitle),
    temperature: 0.7,
    max_tokens: 2048,
    stop: "/n",
  });
  res.status(200).json({ result: completion.data.choices[0].text });
}

function generatePrompt(blogTitle) {
  return `Write an informative blog article containing 500-800 words.

Blog Title: Over-the-counter acne products: What works and why.
/n
Blog article: Many over-the-counter (OTC) acne products are available to treat mild to moderate acne or periodic breakouts. They include cleansing lotions, gels, foams and towelettes, leave-on products, and treatments or kits. How do you know which one is best for you? Before you decide, learn how OTC acne products work and what ingredients to look for. Then develop a gentle skin care regimen to treat and prevent acne. The Food and Drug Administration warns that some popular OTC acne products can cause a serious reaction, including throat tightness and swelling of the face, lips or tongue. This type of reaction is quite rare, so don't confuse it with the redness, irritation or itchiness that may occur where you've applied such products. Active ingredients in acne products Acne products work in different ways, depending on their active ingredients. Some OTC acne products work by killing the bacteria that cause acne inflammation. Others remove excess oil from the skin or speed up the growth of new skin cells and the removal of dead skin cells. Some acne products do a combination of these things. Acne products are just one step in your skin care routine. When using acne products: Wash problem areas twice daily. Use a gentle nonsoap cleanser and don't overdo it. Excessive washing and scrubbing can worsen acne. Scrubs that dissolve during washing are the least abrasive. Scrubs with ground fruit pits and aluminum oxide tend to be more abrasive. Try cleansing cloths or towelettes. These are gentle alternatives to cleansers and washes. Cloths with an open weave are good for dry, sensitive skin. Cloths with a tighter weave are better at removing dead skin cells. Consider pore-clearing adhesive pads. These products (Biore Deep Cleansing Pore Strips, others) are intended to remove dirt, oil and plugs from pores. You apply the strip to wet skin, let it dry and then peel it off. Further study is needed to prove their use in treating and preventing acne. Don't use them more than once every three days. Don't use too much. Apply just enough acne product to cover the problem areas and apply it just after cleansing the skin. Some cloths and towelettes come with benzoyl peroxide and other active ingredients in them, so you don't need to apply more product with these active ingredients after cleansing. Use an oil-free, water-based moisturizer. This helps alleviate dry, peeling skin. Avoid oily cosmetics, sunscreens and hair products. Use products labeled water-based or noncomedogenic. Don't pick or squeeze blemishes. Infection or scarring may result. Watch what touches your face. Keep your hair clean and off your face. Also avoid resting your hand or phone against the side of your face. If your acne doesn't improve after two or three months of home treatment, consider seeing your doctor or a skin specialist (dermatologist) for a prescription lotion or medication.
/n
Blog Title: Dealing with facial redness and rosacea with skincare products
/n
Blog article: There's no “one size fits all” explanation for facial redness. Your face can look red and irritated for many reasons. “What most people refer to as facial redness can be caused by a variety of different skin disorders,” said Dr. Janelle Vega, a board-certified dermatologist. Redness happens! And when it does, there are a few ways to give your skin some much-needed relief. Use soothing ingredients: “Products containing niacinamide, sulfur, allantoin, caffeine, licorice root, chamomile, aloe and cucumber can help reduce redness,” said Dr. David Bank, a board-certified dermatologist in Mount Kisco, New York. Pare down your product routine: If you think your red skin is due to a product allergy or over-exfoliating, it’s time to simplify your product routine. “I usually recommend eliminating all nonessential products in these cases, including makeup to reduce allergen exposure. Once you allow the skin to calm down, then reintroduce products one by one over a period of days to allow for the culprit to identify itself. A visit to a dermatologist or allergist that does patch testing is helpful in causes related to allergies,” Vega said. Get professional help: A dermatologist can help diagnose the exact cause of your red skin and develop a plan to help treat it. Common options for rosacea and eczema include prescription anti-inflammatory creams, oral antibiotics, facials or lasers. Salicylic acid cleansers can help remove dead skin cells and reduce redness in those dealing with seborrheic dermatitis. Should facial redness ever concern you? A little red skin here and there is frustrating, but should it be cause for concern? At the end of the day, it’s up to you to decide if your facial redness is out of character for your skin. “Redness can be a sign of an underlying issue such as lupus, shingles or a systemic allergy such as a medicine reaction. If you have tried over-the-counter remedies without success, see a dermatologist for further evaluation. Even if it isn't one of these more serious conditions, it still might require a prescription,” Bank said.
/n
Blog Title: The morning skincare routine that dermatologists are recommending
/n
Blog article: Morning Skincare Routine. Cleanse. Akhavan recommends that those with acne-prone skin cleanse their face twice a day. He also suggests that if you have oily skin, it's best to kick off your morning skincare routine with a creamy, oil-free cleanser with salicylic acid, such as Clearasil Rapid Rescue Wash, and "avoid using abrasive exfoliant sponges or brushes to minimize traumatic inflammation of the skin." Tone (Optional). "Using toner is an additional step that helps remove extra oil and impurities from the skin as well as rebalance the pH of the skin, which is normally slightly acidic (the ingredients in some cleansers may nudge the skin pH towards basic)," explains Camp. Because some toners can be drying, if you have less oily skin, you may not need to use one. But if you do, he recommends, La Roche-Posay’s Effaclar Clarifying Solution Acne Toner, which contains both salicylic acid (which flushes out pores) and glycolic acid, to help remove dead skin cells that can clog pores and make the skin look dull. Apply Sunscreen. Proper UPF protection is a key step to maintaining healthy skin. Akhavan recommends using a sunscreen "with anti-inflammatory niacinamide in it, such as Elta MD UV Clear." Apply this as a base to be protected from the sun's harmful UVA and UVB rays. Treat/Medicate. The products used in this step may look different for everyone, but Camp says that the morning is a good time to begin targeting new or existing blemishes. "Spot treatments are helpful for zeroing in on acne bumps with products that contain active ingredients like salicylic acid, benzoyl peroxide, and sulfur," he says. He recommends Neutrogena's Rapid Clear Salicylic Acid Acne Treatment with Witch Hazel, or La Roche-Posay’s Effaclar Duo Acne Spot Treatment, which contains 5.5% benzoyl peroxide, "which is effective for inflammatory acne like deep-seated stubborn lesions." Moisturize. Moisturizing your skin is an important final step in your AM routine. But why? "Llipids, or fats, in the top layers of the skin help retain moisture and function to create an impermeable barrier between your skin and the environment," says Camp. "Skipping this step could leave the skin dry, vulnerable to infection, and/or dull in appearance." He recommends that when selecting a product, "look for the words 'non-comedogenic,' which means the product is less likely to clog pores and contribute to the formation of acne papules." Camp is a fan of Elta MD’s UV Clear Broad-Spectrum SPF 46 as well as Cetaphil DermaControl Oil Absorbing Moisturizer SPF 30, which "has a slight mattifying effect helpful for those with oily skin." Now you're ready to apply your favorite oil-free, mineral-based makeup, should you so desire!
/n
Blog title: ${blogTitle}
/n
Blog article:`;
}
